# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-03 03:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20190203_0220'),
        ('rango', '0002_auto_20190202_1617'),
    ]

    operations = [
    ]
