# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-03 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_auto_20190203_2027'),
        ('rango', '0004_auto_20190202_1900'),
    ]

    operations = [
    ]
